import { MyContact } from "./contact"
import { MyHomePage } from "./home"
import { ServicesPage } from "./servicesPage"
import { ServicesParts } from "./services-parts"
import { MyEquipments } from "./equipments"
import { PricePage } from "./price"
import { MyDoctorsPage } from "./doctorsLitPage"
import { DoctorsPage } from "./doctorsPage"
import { SearchPage } from "./searchPage"
import { PolicyPage } from "./policy"
import { AboutPage } from "./about"
export { MyContact, AboutPage, MyHomePage, ServicesPage, ServicesParts, MyEquipments, PricePage, MyDoctorsPage, DoctorsPage, SearchPage, PolicyPage }